-- vaultgear_config.lua
-- Preserved across installer updates. Edited by the monitor UI at runtime.

return {
  schema_version = 1,
  monitor = {
    name = nil,
    text_scale = 0.5,
  },
  runtime = {
    enabled = false,
    scan_interval = 2,
    batch_size = 4,
  },
  routing = {
    input = nil,
    keep = nil,
    trash = nil,
  },
  safety = {
    non_vault_action = "keep",
    unsupported_vault_action = "keep",
    detail_error_action = "keep",
  },
  type_profiles = {
    Gear = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = true,
      keep_soulbound = true,
      keep_unique = true,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
    Tool = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = false,
      keep_soulbound = false,
      keep_unique = false,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
    Jewel = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = false,
      keep_soulbound = false,
      keep_unique = false,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
    Trinket = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = false,
      keep_soulbound = false,
      keep_unique = false,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
    Charm = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = false,
      keep_soulbound = false,
      keep_unique = false,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
    Etching = {
      enabled = true,
      miss_action = "keep",
      unidentified_mode = "keep",
      min_rarity = "ANY",
      min_level = nil,
      max_level = nil,
      min_crafting_potential = nil,
      min_free_repair_slots = nil,
      min_durability_percent = nil,
      max_jewel_size = nil,
      min_uses = nil,
      keep_legendary = true,
      keep_soulbound = false,
      keep_unique = false,
      wanted_modifier_mode = "any",
      wanted_modifiers = {},
      blocked_modifiers = {},
    },
  },
}
