param(
  [string]$InstancePath = 'C:\Users\rboon\AppData\Roaming\PrismLauncher\instances\Vault Paradise',
  [string]$ClientJar = 'C:\Users\rboon\AppData\Roaming\PrismLauncher\libraries\com\mojang\minecraft\1.18.2\minecraft-1.18.2-client.jar',
  [string]$OutputPath = (Join-Path $PSScriptRoot '..\Shared\lib\sound_catalog.lua')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.IO.Compression.FileSystem

function Add-SoundIdsFromArchive {
  param(
    [string]$ArchivePath,

    [System.Collections.Generic.HashSet[string]]$Ids
  )

  $zip = [System.IO.Compression.ZipFile]::OpenRead($ArchivePath)

  try {
    foreach ($entry in $zip.Entries) {
      if ($entry.FullName -notmatch '^assets/([^/]+)/sounds\.json$') {
        continue
      }

      $namespace = $Matches[1]
      $reader = New-Object System.IO.StreamReader($entry.Open())
      try {
        $json = $reader.ReadToEnd() | ConvertFrom-Json
      }
      finally {
        $reader.Close()
      }

      foreach ($property in $json.PSObject.Properties) {
        $key = $property.Name
        if ([string]::IsNullOrWhiteSpace($key)) {
          continue
        }

        if ($key.Contains(':')) {
          [void]$Ids.Add($key)
        }
        else {
          [void]$Ids.Add("$namespace`:$key")
        }
      }
    }
  }
  finally {
    $zip.Dispose()
  }
}

$ids = New-Object 'System.Collections.Generic.HashSet[string]'
$archives = New-Object 'System.Collections.Generic.List[string]'

if (-not (Test-Path -LiteralPath $ClientJar)) {
  throw "Minecraft client jar not found: $ClientJar"
}

$archives.Add($ClientJar)

$modsPath = Join-Path $InstancePath 'minecraft\mods'
if (Test-Path -LiteralPath $modsPath) {
  Get-ChildItem -LiteralPath $modsPath -Filter '*.jar' -File | ForEach-Object {
    $archives.Add($_.FullName)
  }
}

$packsPath = Join-Path $InstancePath 'minecraft\resourcepacks'
if (Test-Path -LiteralPath $packsPath) {
  Get-ChildItem -LiteralPath $packsPath -File | Where-Object {
    $_.Extension -in @('.zip', '.jar')
  } | ForEach-Object {
    $archives.Add($_.FullName)
  }
}

foreach ($archive in $archives) {
  Add-SoundIdsFromArchive -ArchivePath $archive -Ids $ids
}

$sortedIds = @($ids) | Sort-Object
$namespaceCounts = @{}

foreach ($soundId in $sortedIds) {
  $namespace = $soundId.Split(':')[0]
  if (-not $namespaceCounts.ContainsKey($namespace)) {
    $namespaceCounts[$namespace] = 0
  }
  $namespaceCounts[$namespace] += 1
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine('-- Auto-generated by scripts/generate-sound-catalog.ps1')
[void]$builder.AppendLine('local M = {}')
[void]$builder.AppendLine()
[void]$builder.AppendLine(("M.GENERATED_AT = '{0}'" -f (Get-Date).ToString('yyyy-MM-dd HH:mm:ss K')))
[void]$builder.AppendLine(("M.SOUND_COUNT = {0}" -f $sortedIds.Count))
[void]$builder.AppendLine(("M.ARCHIVE_COUNT = {0}" -f $archives.Count))
[void]$builder.AppendLine('M.NAMESPACE_COUNTS = {')

foreach ($namespace in ($namespaceCounts.Keys | Sort-Object)) {
  [void]$builder.AppendLine(("  ['{0}'] = {1}," -f $namespace, $namespaceCounts[$namespace]))
}

[void]$builder.AppendLine('}')
[void]$builder.AppendLine('M.SOUNDS = {')

foreach ($soundId in $sortedIds) {
  [void]$builder.AppendLine(("  '{0}'," -f $soundId.Replace("'", "\'")))
}

[void]$builder.AppendLine('}')
[void]$builder.AppendLine()
[void]$builder.AppendLine('return M')

$targetDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $targetDir)) {
  New-Item -ItemType Directory -Path $targetDir | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $builder.ToString(), $utf8NoBom)

Write-Output ("Wrote {0} sounds from {1} archives to {2}" -f $sortedIds.Count, $archives.Count, $OutputPath)
